### ISSUE TITLE
Error in Ansible-script

### ISSUE THREAD

**Issue by miyamam** [derdanu/azure-openshift#1]
After deployed VMs on Azure, at master node. Run./openshift-install.sh
The following error message has shown.

```

 ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/opt/openshift-ansible/playbooks/byo/openshift-cluster/config.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include: ../../common/openshift-cluster/config.yml
  ^ here

```

There is some issue on ansible playbook.

**Comment by derdanu** [comment]
With the new Epel repository by default ansible2 is installed and we ran into this error https://github.com/ansible/ansible/issues/14987 

I have changed the master custom script to use version 1.9 of ansible by default. https://github.com/derdanu/azure-openshift/commit/f7e0d59302bfef0eeca14c698ca43b6b4fd4df1f
