### ISSUE TITLE
/openshift-install.sh command not found

### ISSUE THREAD

**Issue by julienstroheker** [derdanu/azure-openshift#5]
After the deployment, when I run the ./openshift-install.sh I have the following message : 

```
./openshift-install.sh: line 2: ansible-playbook: command not found
./openshift-install.sh: line 3: oadm: command not found
./openshift-install.sh: line 4: oadm: command not found
```
Thanks

**Comment by julienstroheker** [comment]
Seems working when I changed the epel repo from 7.8 to epel-release-7-9.noarch.rpm
I forked the project and testing it

**Comment by derdanu** [comment]
Nice catch, they bumped up the epel version. I have changed it.
